### ISSUE TITLE
Expected behavior?

### ISSUE THREAD

**Issue by jumpingfella** [chicago-joe/High-Frequency-Trading-Model-with-IB#5]
Hello,

I'm trying to run your software, so far it only prints out the following:
[2020-03-17 13:24:55.526923][strategy params]beta:1.40 volatility:nan|rpnl=0.00

And that's it, nothing else happens. Is it supposed to be like this?

**Comment by chicago-joe** [comment]
definitely not. I'm working on improving the strategy parameters and pairs trading methodology as a whole, be on the lookout for an update in the coming days
